import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";

export const runtime = "nodejs";

function generatePdfHTML(data: any[], type: string): string {
  const timestamp = new Date().toLocaleString();

  let tableRows = "";

  if (type === "catalog") {
    tableRows = data
      .map(
        (item) => `
      <tr>
        <td>${item.partNumber || ""}</td>
        <td>${item.commonNameEn || ""}</td>
        <td>${item.commonNameTh || ""}</td>
        <td>${item.uom || ""}</td>
        <td>${item.characteristicsEn || ""}</td>
        <td>${item.createdAt || ""}</td>
      </tr>
    `
      )
      .join("");

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>My Catalog Export</title>
        <style>
          * { margin: 0; padding: 0; }
          body { font-family: Arial, sans-serif; color: #333; background: white; }
          .container { padding: 40px; max-width: 1200px; margin: 0 auto; }
          h1 { color: #2c3e50; margin-bottom: 10px; border-bottom: 3px solid #9b59b6; padding-bottom: 10px; }
          .meta { color: #7f8c8d; font-size: 12px; margin-bottom: 20px; }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          th {
            background-color: #9b59b6;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
            border-bottom: 2px solid #8e44ad;
          }
          td {
            padding: 10px 12px;
            border-bottom: 1px solid #ecf0f1;
          }
          tr:nth-child(even) {
            background-color: #f8f9fa;
          }
          tr:hover {
            background-color: #f0e6f6;
          }
          .total { margin-top: 20px; font-weight: bold; color: #2c3e50; }
          footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #95a5a6; font-size: 11px; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>📚 My Catalog</h1>
          <div class="meta">
            <p>Exported: ${timestamp}</p>
            <p>Total Items: ${data.length}</p>
          </div>
          
          <table>
            <thead>
              <tr>
                <th>Part Number</th>
                <th>Common Name (EN)</th>
                <th>Common Name (TH)</th>
                <th>UOM</th>
                <th>Characteristics</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows}
            </tbody>
          </table>
          
          <div class="total">Total Items: ${data.length}</div>
          
          <footer>
            <p>This report was automatically generated by BIR Part Generator</p>
          </footer>
        </div>
      </body>
      </html>
    `;
  } else {
    // saved-parts
    tableRows = data
      .map(
        (item) => `
      <tr>
        <td>${item.partNumber}</td>
        <td>${item.commonNameEn || ""}</td>
        <td>${item.commonNameTh || ""}</td>
        <td>${item.uom || ""}</td>
        <td>${item.eccn || ""}</td>
        <td>${item.hts || ""}</td>
        <td>${item.coo || ""}</td>
        <td>${item.createdBy || ""}</td>
        <td>${item.createdAt}</td>
      </tr>
    `
      )
      .join("");

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Saved Parts Export</title>
        <style>
          * { margin: 0; padding: 0; }
          body { font-family: Arial, sans-serif; color: #333; background: white; }
          .container { padding: 40px; max-width: 1400px; margin: 0 auto; }
          h1 { color: #2c3e50; margin-bottom: 10px; border-bottom: 3px solid #9b59b6; padding-bottom: 10px; }
          .meta { color: #7f8c8d; font-size: 12px; margin-bottom: 20px; }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            font-size: 11px;
          }
          th {
            background-color: #9b59b6;
            color: white;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            border-bottom: 2px solid #8e44ad;
          }
          td {
            padding: 8px 10px;
            border-bottom: 1px solid #ecf0f1;
          }
          tr:nth-child(even) {
            background-color: #f8f9fa;
          }
          tr:hover {
            background-color: #f0e6f6;
          }
          .total { margin-top: 20px; font-weight: bold; color: #2c3e50; }
          footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #95a5a6; font-size: 11px; text-align: center; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>💾 Saved Parts (Global)</h1>
          <div class="meta">
            <p>Exported: ${timestamp}</p>
            <p>Total Items: ${data.length}</p>
          </div>
          
          <table>
            <thead>
              <tr>
                <th>Part Number</th>
                <th>Common Name (EN)</th>
                <th>Common Name (TH)</th>
                <th>UOM</th>
                <th>ECCN</th>
                <th>HTS</th>
                <th>COO</th>
                <th>Created By</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows}
            </tbody>
          </table>
          
          <div class="total">Total Items: ${data.length}</div>
          
          <footer>
            <p>This report was automatically generated by BIR Part Generator</p>
          </footer>
        </div>
      </body>
      </html>
    `;
  }
}

export async function GET(req: Request) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const type = searchParams.get("type") || "catalog";

    let data: any[] = [];

    if (type === "catalog") {
      const favorites = await prisma.savedPartFavorite.findMany({
        where: { userId: user.id },
        include: { glossary: true, global: true },
        orderBy: { createdAt: "desc" },
      });

      data = favorites.map((fav) => {
        const item = fav.glossary || fav.global;
        return {
          partNumber: item?.partNumber || "",
          commonNameEn: item?.commonNameEn || "",
          commonNameTh: item?.commonNameTh || "",
          uom: item?.uom || "",
          characteristicsEn: item?.characteristicsOfMaterialEn || "",
          characteristicsTh: item?.characteristicsOfMaterialTh || "",
          createdAt: new Date(fav.createdAt).toLocaleDateString(),
        };
      });
    } else if (type === "saved-parts") {
      const parts = await prisma.savedPartGlobal.findMany({
        orderBy: { createdAt: "desc" },
      });

      data = parts.map((part) => ({
        partNumber: part.partNumber,
        commonNameEn: part.commonNameEn || "",
        commonNameTh: part.commonNameTh || "",
        uom: part.uom || "",
        eccn: part.eccn || "",
        hts: part.hts || "",
        coo: part.coo || "",
        createdBy: part.createdByName || "",
        createdAt: new Date(part.createdAt).toLocaleDateString(),
      }));
    }

    const html = generatePdfHTML(data, type);

    // ใช้ html2pdf จาก CDN (เรนเดอร์ HTML เป็น PDF ที่ client-side)
    const filename = `${type}-export-${new Date().toISOString().split("T")[0]}.pdf`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
      },
    });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message }, { status: 500 });
  }
}
